#! /usr/bin/env python
# -*- coding: utf-8 -*-
"""
Parse and prepare the Consumer Price Index (CPI) dataset.
"""
import os
import csv
import collections
from datetime import date


class Area(object):
    """
    A geographical area where prices are gathered monthly.
    """
    def __init__(self, code, name):
        self.code = code
        self.name = name

    def __repr__(self):
        return "<Area: {}>".format(self.__str__())

    def __str__(self):
        return self.name


class Series(object):
    """
    A set of CPI data observed over an extended period of time over consistent time intervals ranging from
    a specific consumer item in a specific geographical area whose price is gathered monthly to a category
    of worker in a specific industry whose employment rate is being recorded monthly, etc.

    Yes, that's the offical government definition. I'm not kidding.
    """
    def __init__(self, id):
        self.id = id

    def __repr__(self):
        return "<Series: {}>".format(self.__str__())

    def __str__(self):
        return self.id

    @property
    def survey_code(self):
        return self.id[:2]

    @property
    def seasonal_code(self):
        return self.id[2:3]

    @property
    def periodicity_code(self):
        return self.id[3:4]

    @property
    def area_code(self):
        return self.id[4:8]

    @property
    def item_code(self):
        return self.id[8:]


class Index(object):
    """
    A Consumer Price Index value generated by the Bureau of Labor Statistics.
    """
    def __init__(self, series, date, year, period_type, value):
        self.series = series
        self.date = date
        self.year = year
        self.period_type = period_type
        self.value = value

    def __repr__(self):
        return "<Index: {}>".format(self.__str__())

    def __str__(self):
        return "{} ({}): {}".format(self.date, self.period_type, self.value)


class Data(object):
    THIS_DIR = os.path.dirname(__file__)
    FILE_LIST = [
        "cu.area",
        "cu.series",
        "cu.data.1.AllItems",
    ]

    def __init__(self):
        self.file_dict = dict(
            (file, self.get_file(file)) for file in self.FILE_LIST
        )
        self.areas = collections.defaultdict(collections.OrderedDict)
        self.by_year = collections.defaultdict(collections.OrderedDict)
        self.by_month = collections.defaultdict(collections.OrderedDict)

    def get_file(self, file):
        """
        Returns the CPI data as a csv.DictReader object.
        """
        # Open up the CSV from the BLS
        csv_path = os.path.join(self.THIS_DIR, "{}.csv".format(file))
        csv_file = open(csv_path, "r")
        return csv.DictReader(csv_file)

    def parse_periodtype(self, period):
        """
        Accepts a row from the raw BLS data. Returns a string classifying the period.
        """
        period_types = dict(("M{:02d}".format(i), "monthly") for i in range(1, 13))
        period_types["M13"] = "annual"
        period_types.update({
            "S01": "half",
            "S02": "half",
            "S03": "annual"
        })
        return period_types[period]

    def parse_date(self, row):
        """
        Accepts a row from the raw BLS data. Returns a Python date object based on its period.
        """
        # If it is annual data, return it as Jan. 1 of that year.
        if row['period'] in ['M13', 'S03']:
            return date(int(row['year']), 1, 1)
        # If it is month data, return it as the first day of the month.
        elif row['period'].startswith("M"):
            return date(int(row['year']), int(row['period'].replace("M", "")), 1)
        # If it's data for halves of the year...
        else:
            months = {
                "S01": 1,
                "S02": 7,
            }
            return date(int(row['year']), months[row['period']], 1)

    def parse(self):
        """
        Parse the raw BLS data into dictionaries for Python lookups.
        """
        for row in self.file_dict['cu.area']:
            area = Area(row['area_code'], row['area_name'])
            self.areas[area.code] = area

        for row in self.file_dict["cu.data.1.AllItems"]:
            # Create a series
            series = Series(row['series_id'])
            series.area = self.areas[series.area_code]

            # Clean up the values
            period_type = self.parse_periodtype(row['period'])
            date = self.parse_date(row)

            # Create an object
            index = Index(
                series,
                date,
                date.year,
                period_type,
                float(row['value'])
            )

            # Sort it to the proper lookup
            if index.period_type == 'annual':
                self.by_year[series.id][index.year] = index
            elif index.period_type == 'monthly':
                self.by_month[series.id][index.date] = index


data = Data()
data.parse()
cpi_by_year = data.by_year
cpi_by_month = data.by_month
areas = data.areas.values()
